Lab5
polinabogd/Lab5_2020 pull request #1
Opened 2020-11-30 13:37 UTC by polinabogd

2020-12-11 09:01 UTC, yeldmitrenko requested changes
Please fix my comments

2020-12-11 19:11 UTC, yeldmitrenko requested changes
Please fix my comments

2020-12-11 19:11 UTC, yeldmitrenko commented on lab5.h
> +        cout<<hh<<":"<<mm<<":"<<ss<<endl;
You should rewrite it from "`cout<<hh<<":"<<mm<<":"<<ss<<endl;`" to "`cout << hh << ":" << mm << ":"<< ss << endl;`"

2020-12-11 19:11 UTC, yeldmitrenko commented on lab5.h
> +        ss = trunc(mm%60);
Please make spaces on both sides of "%"

2020-12-11 19:11 UTC, yeldmitrenko commented on lab5.h
> +        cout<<hh*3600 + mm*60 + ss<<endl;
Please make it clear, what is it 3600 and what is it 60. It should be better to write constant at the beginning of the file. Moreover, please make spaces on both sides of "*" and add spaces between "cout", "<<", "hh" and "ss", "<<", "endl;"

2020-12-13 16:40 UTC, polinabogd commented on lab5.h
> +    {
In this case i find it better to leave the implementation inside of the class.

2020-12-13 16:52 UTC, yeldmitrenko approved these changes

2020-12-13 16:52 UTC, yeldmitrenko commented on lab5.h
> +    void ConvertTime(int ss)
Remove the class method to 1 tab to the right

2020-12-13 16:52 UTC, yeldmitrenko commented on lab5.h
> +    void ConvertTime(int hh, int mm, int ss)
Remove the class method to 1 tab to the right

2021-04-06 19:55 UTC, merged